### PR TITLE
New Dockerfile using alpine-golang-make-onbuild base image

### PR DESCRIPTION
**Pull request by sdurrheimer**
Following the docker related PR series.

New Dockerfile using the [alpine-golang-make-onbuild](https://github.com/sdurrheimer/alpine-golang-make-onbuild) base image whose goal is to unified the way to dockerize prometheus tools and exporters based on Golang.

The binary is build using make. (Golang is installed via make too, respecting the GO_VERSION).

A testable image is available under my name on Docker hub : [Link](https://registry.hub.docker.com/u/sdurrheimer/prom2json/)

I have also added some Docker usage instructions in the readme.

As always, the [alpine-golang-make-onbuild](https://github.com/sdurrheimer/alpine-golang-make-onbuild)  image can be also move under Prometheus organization.

@beorn7 @discordianfish

### CODE REVIEW

**Comment by beorn7** [comment]
Just curious: Does it make sense to deploy a simple command line tool as a Docker image?

@discordianfish As in the other PR, I'd be delighted to receive your input.

**Comment by sdurrheimer** [comment]
Yes, I think it makes sense, it can be dockerize like any other software. Moreover, it's useful for people running docker based OS like RancherOS or CoreOS for example.

**Comment by sdurrheimer** [comment]
And, the base image does all the job, so it doesn't cost much to add it I guess.

**Comment by sdurrheimer** [comment]
Sorry miss click.

**Pull request merged**
