### PR TITLE
Fix CircleCI job to publish container images

### PR DESCRIPTION
**Pull request by simonpasquier**
cc @SuperQ  @beorn7

### CODE REVIEW

**Comment by simonpasquier** [comment]
Wait, it isn't the correct fix...

**Comment by beorn7** [comment]
In other repos, `$CIRCLE_TAG` is used.

**Comment by simonpasquier** [comment]
@beorn7 yes I went too fast. It should be good now...

**Comment by beorn7** [comment]
Will merge on green. Thank you very much.

Now the question is how to trigger a docker-publish for v1.2.0 (which in itself still has the broken config).

**Pull request merged**
