### PR TITLE
allow extra headers to be passed in when fetching metrics from target…

### PR DESCRIPTION
**Pull request by yyzh1**
… URLs, for purposes like authentications

### CODE REVIEW

**Comment by yyzh1** [comment]
I saw some discussions around allowing headers to be added but did not find any changes followed. Attempting with a PR to see if this makes sense as a starting point. 
Please let me know if it conflicts with any ongoing efforts...
Thank you!

**Comment by beorn7** [comment]
When more and more requests came in to configure the exact nature of the HTTP request, we decided to simply use `curl` and pipe the result into `prom2json`. If you search for "Advanced HTTP through curl" in the README.md, you'll see an example.

Otherwise, we are doomed to iteratively reimplement significant parts of `curl`.

I would like to stick with that philosophy. (And if we had had that insight earlier, some of the already added features would not have been added. But now we cannot rip them out without a breaking change.)

**Comment by yyzh1** [comment]
thank you for the details. that makes sense. only thing missing with the curl approach is that it has to be used together with the main function, which doesn't let the prom2json.go to be used as a lib with a different main function for things like running it as a web service, etc. But i guess it's also debatable whether that's worth the trouble. thanks!

**Comment by beorn7** [comment]
Yeah, the usage as a library is a valid point. I have a vague memory that this had been discussed before, but I cannot find it right now. Perhaps it was on the mailing list and not here in an issue or PR.

Here my reasoning:

If we wanted to make `FetchMetricFamilies` more flexible, we would probably not add more parameters to the function, but simply ask the caller to create their own `http.Client` and pass it in instead of the URL as a string. However, this cuts out 6 lines from the function, leaving only 13 lines (of which 8 are error handling).
So what you could already do right now is to not call `FetchMetricFamilies` at all but `ParseResponse`, or in other words, do the HTTP handling completely on your side, which gives you all the flexibility you want, and only leave the parse logic to `prom2json` by calling `ParseResponse` with the `http.Response`.

**Comment by yyzh1** [comment]
that makes sense. even if `FetchMetricsFamilies` takes `http.Client`, there might still be occasions where people only want to add headers, etc, and  `ParseResponse` seems to be a good way to work around this.

btw on a separate topic, do we see value in adding support to make prom2json a service, besides output in stdout?

**Comment by beorn7** [comment]
What do you mean by "make prom2json a service"?

**Comment by yyzh1** [comment]
sorry, I meant to ask whether we see any value making this an API service, which takes an HTTP request and then scrapes a target with metrics and return json format metrics.

**Comment by yyzh1** [comment]
Makes sense, thank you for the details.

**Pull request closed without merging**
