### PR TITLE
added close idle client connections

### PR DESCRIPTION
**Pull request by maxim0r**

### CODE REVIEW

**Comment by beorn7** [comment]
Hmm, could you explain why you need this?

In my understanding, if prom2json is used as the command line tool it is, it should close all the idle connections when it exits (but I might be wrong). On the other hand, if people use this code as a library, they might not want the connection to get closed because they want to reuse it.

In different news, the go.mod file is now pointing to your own repo. I recommend not to update go.mod in this PR as it is unrelated to the change.

**Comment by maxim0r** [comment]
I use prom2json as a library to translate the necessary metrics to legacy zabbix. I noticed that open connections are accumulating. I do not need to reuse the connection. I'm a newbie in Go, I don’t know how to clear the connections outside the library :(

> In different news, the go.mod file is now pointing to your own repo. I recommend not to update go.mod in this PR as it is unrelated to the change.

Sorry, I updated go.mod in my fork not in PR. I did not think that it will link. I deleted the last commit.

**Comment by maxim0r** [comment]
I call this function via ticker
```go
func getMetrics(ctx context.Context, url string, to time.Duration) (map[string]*prom2json.Family, error) {
	mfChan := make(chan *dto.MetricFamily, 1024)

	ctx, cancel := context.WithTimeout(ctx, to)
	defer cancel()

	go func() {
		err := prom2json.FetchMetricFamilies(url, mfChan, "", "", true)
		if err != nil {
			log.Errorf("fetch metrics error: %s", err)
			return
		}
	}()

	result := make(map[string]*prom2json.Family)
	for {
		select {
		case <-ctx.Done():
			log.Errorf("fetch metrics context cancel")
			return nil, ctx.Err()
		case mf := <-mfChan:
			if mf == nil {
				return result, nil
			}
			result[*mf.Name] = prom2json.NewFamily(mf)
		}
	}
}
```

**Comment by beorn7** [comment]
Thanks for the code. I think I understand the problem.

You are in fact interested in re-using the connection, but the code doesn't allow it because `FetchMetricFamilies` creates a new transport on each call. In the command line tool `prom2json`, it doesn't matter, because it is only called once. But in your case, a new transport with new connections, that are kept alive, is created.

I have created #50 , which should solve your problem. In your case, you can just use `nil` as the Transport.

**Comment by beorn7** [comment]
I assume this is superseded by #50 . @maxim0r please follow up if you think otherwise.

**Comment by maxim0r** [comment]
Everything is good. Thank you very much for the help.

>In your case, you can just use nil as the Transport.

I have a panic on nil Transport, so I create an instance for this.

**Comment by beorn7** [comment]
> I have a panic on nil Transport

Oops, that's a bug. I'll send you another PR. Thanks for noticing.

**Pull request closed without merging**
